spring:
  application:
    name: http-client-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/store
    username: root
    password: myrootpass

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    # NULL 값을 위한 JDBC 타입 설정 : null값이 있을 경우 NULL로 설정
    jdbc-type-for-null: NULL
    # 언더스코어를 카멜 케이스로 맵핑 설정
    map-underscore-to-camel-case: true

springdoc:
  packages-to-scan: com.http.client.httpclientproject
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: http-client-project swagger
  version: v1.0.0
  description: http-client project description
  cache:
    disabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true

server:
  port: 8080