spring:
  application:
    name: http-client-project

springdoc:
  packages-to-scan: com.http.client.httpclientproject
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: http-client-project swagger
  version: v1.0.0
  description: http-client project description
  cache:
    disabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true

server:
  port: 8080